version: "3.1"

services:
  database:
    image: postgres
    container_name: go-database
    restart: always
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
